import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import createRoom from "../utils/createRoom";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ newRoom }: any) {
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(false);
  const [room, setRoom] = useState<any>(undefined);

  const getNewRoom = () => {
    setLoading(true);
    router.replace(router.asPath);
  };

  useEffect(() => {
    setRoom(newRoom);
    console.log(newRoom);
    setLoading(false);
  }, [newRoom]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {loading ? "Loading.." : ""}
        <button onClick={getNewRoom}>Get new room</button>
        <h1>{newRoom?._id}</h1>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  let newRoom = undefined;
  const response = await fetch("http://localhost:3000/api/rooms/", {
    method: "GET",
    headers: {
      Accept: "*/*",
    },
  });
  const rooms = await response.json();

  if (rooms.length > 0) {
    newRoom = rooms[0];
  } else {
    const room = await createRoom();
    newRoom = room;
  }

  return {
    props: {
      newRoom: newRoom,
    },
  };
}
